openapi: 3.0.0
info:
  title: Epic Microservice
  version: 1.0.0
  description: Documentation for Epic Microservice.
  contact:
    name: Vidhin
    email: vidhin@asu.edu
servers:
  - url: http://localhost:3006
  - url: http://localhost:8080

paths:
  /createEpic:
    post:
      summary: Create new Epic.
      description: Create a new Epic by providing the username, password, token, projectId, Epic name, and description in the request body..
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Taiga username
                  example: SERtestuser
                password:
                  type: string
                  description: Taiga password
                  example: testuser
                token:
                  type: string
                  description: Taiga token
                projectId:
                  type: number
                  description: Project id in which epic is to be created
                  example: 722556
                name:
                  type: string
                  description: Epic name
                  example: testEpic
                description:
                  type: string
                  description: Epic description
                  example: test Epic description
              required:
                - username
                - password
                - projectId
                - name
                - description
      responses:
        "201":
          description: Epic successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  EpicId:
                    type: number
                    example: 187831
                  EpicName:
                    type: string
                    example: testEpic
                  description:
                    type: string
                    example: testEpic description
        "500":
          description: Error creating Epic.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Error creating Epic
      tags:
        - Epic create
  /listEpics:
    post:
      summary: List all Epics.
      description: List all Epics by providing the username, password, token, projectId, projectSlug, assignedTo, isClosed in the request body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Taiga username
                  example: SERtestuser
                password:
                  type: string
                  description: Taiga password
                  example: testuser
                token:
                  type: string
                  description: Taiga token
                projectId:
                  type: number
                  description: Project id whose epics are to be listed
                  example: 722556
                projectSlug:
                  type: string
                  description: Project slug whose epics are to be listed
                  example: testproject
                assignedTo:
                  type: string
                  description: User id whose epics are to be listed
                  example: 1
                isClosed:
                  type: boolean
                  description: If true, closed epics are listed
                  example: false
              required:
                - username
                - password
      responses:
        "200":
          description: Epics successfully listed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  epics:
                    type: array
                    items:
                      type: object
                      description: https://docs.taiga.io/api.html#object-epic-detail-list
        "500":
          description: Error listing Epics.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  epics:
                    type: array
                    description: Empty array
      tags:
        - Epic list
  /getEpic:
    post:
    summary: Get Epic details.
    description: Get Epic details by providing the username, password, token, epicId in the request body.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                description: Taiga username
                example: SERtestuser
              password:
                type: string
                description: Taiga password
                example: testuser
              token:
                type: string
                description: Taiga token
              epicId:
                type: number
                description: Epic id whose details are to be fetched
                example: 187831
            required:
              - username
              - password
              - epicId
    responses:
      "200":
        description: Epic details successfully fetched.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                epic:
                  type: object
                  description: https://docs.taiga.io/api.html#object-epic-detail-get
      "500":
        description: Error fetching Epic details.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                epic:
                  type: object
                  description: Empty object