openapi: 3.0.0
info:
  title: Tasks Microservice
  version: 1.0.0
  description: Documentation for Task Microservice
  contact:
    name: Team Morpheus
    email: skuma251@asu.edu
servers:
  - url: http://localhost:3005
  - url: http://localhost:8080
paths:
  /createTask:
    post:
      summary: Create new task by passing project name and user story name 
      description: Creating new task based on username, password, project name and user story name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                projectname:
                  type: string
                userstoryname:
                  type: string
                taskname:
                  type: string
              required:
                - username
                - password
                - projectname
                - userstoryname
                - taskname
                
      responses:
        "200":
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  taskId:
                    type: string
        "401":
          description: Task Creation Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  taskId:
                    type: string
      tags:
        - task service

  /updateTask:
    post:
      summary: Update existing task details 
      description: Update existing task based on the status, description 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                projectname:
                  type: string
                userstoryname:
                  type: string
                taskname:
                  type: string
                description:
                  type: string
                status:
                  type : string
              required:
                - username
                - password
                - projectname
                - userstoryname
                - taskname
                - description
                - status
                
      responses:
        "200":
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  taskId:
                    type: string
        "401":
          description: Task Creation Failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  taskId:
                    type: string
      tags:
        - task service