openapi: 3.0.0
info:
  title: Project Microservice
  version: 1.0.0
  description: Documentation for Project Microservice.
  contact:
    name: Team Morpheus
    email: skuma251@asu.edu
servers:
  - url: http://localhost:3002
  - url: http://localhost:8080

paths:
  /getProjectBySlug:
    get:
      summary: Get project by slug name
      description: Get project data by providing the username, password, and project name in the request body. Slug name will be formed by combining the username and project name.
      parameters:
        - name: username
          in: query
          required: true
          description: Taiga username
          schema:
            type: string
        - name: password
          in: query
          required: true
          description: Taiga password
          schema:
            type: string
        - name: name
          in: query
          required: true
          description: Project name
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  projectId:
                    type: number
                    example: 715454
                  projectName:
                    type: string
                    example: testProject
                  slugName":
                    type: string
                    example: sertestuser-testproject
                  description:
                    type: string
                    example: testProject

        "404":
          description: Project not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Error getting project by name

  /createProject:
    post:
      summary: Create new project.
      description: Create a new project by providing the username, password, project name, and description in the request body..
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Taiga username
                  example: SERtestuser
                password:
                  type: string
                  description: Taiga password
                  example: testuser
                name:
                  type: string
                  description: Project name
                  example: testProject
                description:
                  type: string
                  description: Project description
                  example: test project
              required:
                - username
                - password
                - name
                - description
      responses:
        "201":
          description: Project successfully created.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  projectId:
                    type: number
                    example: 715454
                  projectName:
                    type: string
                    example: testProject
                  slugName":
                    type: string
                    example: sertestuser-testproject
                  description:
                    type: string
                    example: testProject
        "500":
          description: Error creating project.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Error creating userstory
      tags:
        - project
