openapi: 3.0.0
info:
  title: CFD Microservice
  version: 1.0.0
  description: Documentation for CFD (Cumulative Flow Diagram) Microservice
  contact:
    name: Raumil Dhandhukia
    email: rdhandhu@asu.edu
servers:
  - url: http://localhost:3012
  - url: http://localhost:8080
paths:
  /cfd:
    post:
      summary: Get tasks status matrix for to create CFD.
      description: Based upon Project Name, status matrix for past seven days will be returned to the called to create CFD.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectName: 
                  type: string
                  description: Project Name
                  example: Test Project
                username: 
                  type: string
                  description: User Name
                  example: sertestuser
                password: 
                  type: string
                  description: Password
                  example: test
                
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                "Tue Apr 11 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 1
                  Closed: 0
                  Done: 0
                  In progress: 5
                  New: 9
                  Needs Info: 2
                "Wed Apr 12 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 1
                  Closed: 0
                  Done: 0
                  In progress: 11
                  New: 4
                  Needs Info: 1
                "Thu Apr 13 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 1
                  Closed: 0
                  Done: 0
                  In progress: 11
                  New: 6
                  Needs Info: 1
                "Fri Apr 14 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 1
                  Closed: 0
                  Done: 0
                  In progress: 17
                  New: 1
                  Needs Info: 2
                "Sat Apr 15 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 1
                  Closed: 0
                  Done: 0
                  In progress: 20
                  New: 0
                  Needs Info: 0
                "Sun Apr 16 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 2
                  Closed: 0
                  Done: 2
                  In progress: 22
                  New: 0
                  Needs Info: 1
                "Mon Apr 17 2023 16:52:36 GMT-0700 (Mountain Standard Time)":
                  Ready for test: 2
                  Closed: 0
                  Done: 0
                  In progress: 26
                  New: 2
                  Needs Info: 0
        "500":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Project not found
      tags:
        - CFD Microservice