version: "3"
services:
  authservice:
    build: ./authservice
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - my-network
  projectservice:
    build: ./projectservice
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - my-network
  userstoryservice:
    build: ./userstoryservice
    ports:
      - "3003:3003"
    env_file:
      - .env
  taskservice:
    build: ./taskservice 
    ports:
      - "3004:3004"
    env_file:
      - .env
    networks:
      - my-network
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - authservice
      - projectservice
      - userstoryservice
networks:
  my-network:
