version: '3'
services:
  authservice:
    build: ./authservice
    ports:
      - '3001:3001'
    env_file:
      - .env
    networks:
      - my-network
  autopilot:
    build: ./autoPilot
    ports:
      - '3015:3015'
    env_file:
      - .env
    networks:
      - my-network
  projectservice:
    build: ./projectservice
    ports:
      - '3002:3002'
    env_file:
      - .env
    networks:
      - my-network
<<<<<<< HEAD

=======
  cfdservice:
    build: ./cfdservice
    ports:
      - "3012:3012"
    networks:
      - my-network
>>>>>>> f1c4c9e631d93cd7b0c216cf3b3ff05dc64388d5
  rolesservice:
    build: ./rolesservice
    ports:
      - '3008:3008'
    env_file:
      - .env
    networks:
      - my-network
  userstoryservice:
    build: ./userstoryservice
    ports:
      - '3003:3003'
    env_file:
      - .env
    networks:
      - my-network
  taskservice:
    build: ./taskservice
    ports:
      - '3005:3005'
    env_file:
      - .env
    networks:
      - my-network
  epicservice:
    build: ./epicservice
    ports:
      - '3006:3006'
    env_file:
      - .env
    networks:
      - my-network
  memberservice:
    build: ./memberservice
    ports:
      - '3004:3004'
    env_file:
      - .env
    networks:
      - my-network
  sprintservice:
    build: ./sprintservice
    ports:
      - '3010:3010'
    env_file:
      - .env
    networks:
      - my-network
<<<<<<< HEAD
=======
  issueservice:
    build: ./issueservice
    ports:
      - "3009:3009"
    env_file:
      - .env    
    networks:
      - my-network           
>>>>>>> f1c4c9e631d93cd7b0c216cf3b3ff05dc64388d5
  api-gateway:
    build: ./api-gateway
    ports:
      - '8080:8080'
    env_file:
      - .env
    networks:
      - my-network
    depends_on:
      - authservice
      - projectservice
      - userstoryservice
      - memberservice
      - taskservice
      - rolesservice
<<<<<<< HEAD
      - autopilot
=======
      - issueservice
>>>>>>> f1c4c9e631d93cd7b0c216cf3b3ff05dc64388d5
networks:
  my-network:
