version: "3"
services:
  authservice:
    build: ./authservice
    ports:
      - "3001:3001"
    env_file:
      - .env
  projectservice:
    build: ./projectservice
    ports:
      - "3002:3002"
    env_file:
      - .env
  userstoryservice:
    build: ./userstoryservice
    ports:
      - "3003:3003"
    env_file:
      - .env
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - authservice
      - projectservice
      - userstoryservice
