version: "3"
services:
  authservice:
    build: ./authservice
    ports:
      - "3000:3000"
  projectservice:
    build: ./projectservice
    ports:
      - "3001:3001"
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - authservice
      - projectservice
