http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: "/ip"
  authservice:
    host: localhost
    paths: "/authenticate"
  projectservice:
    host: localhost
    paths: "/createProject"
  getProjectByslug:
    host: localhost
    paths: "/getProjectByslug"
    appendQueryString: true
  getProject:
    host: localhost
    paths: "/getProject"
    appendQueryString: true
  userstoryservice:
    host: localhost
    paths: "/createUserstory"
  taskservice:
    host: localhost
    paths: "/createTask"
  deleteTask:
    host: localhost
    paths: "/deleteTask"
  updateuserstory:
    host: localhost
    paths: "/updateUserstory"
  getuserstoriesdetails:
    host: localhost 
    paths: "/getAllUserStoryDetails"
  epicservice:
    host: localhost
    paths: "/createEpic"

  memberservice:
    host: localhost
    paths: "/createMember"
  getMembers:
    host: localhost
    paths: "/getMembers"
  deleteMembers:
    host: localhost
    paths: "/deleteMember/:id"
  editMemberRole:
    host: localhost
    paths: "/editMemberRole"  

  sprintservice:
    host: localhost
    paths: "/sprints" 
  sprintByID:
    host: localhost  
    paths: "/sprintByID/:sprintId"
  createSprint:
    host: localhost
    paths: "/createSprint"
  editSprint:
    host: localhost  
    paths: "/editSprint/:sprintId"
  deleteSprint:
    host: localhost
    paths: "/deleteSprint/:sprintId"
  sprintByName:
    host: localhost
    paths: "/sprintByName"
  editSprintByName:
    host: localhost
    paths: "/editSprintByName"
  deleteSprintByName:
    host: localhost
    paths: "/deleteSprintByName"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  authservice:
    url: "http://authservice:3001"
  projectservice:
    url: "http://projectservice:3002"
  userstoryservice:
    url: "http://userstoryservice:3003"
  epicservice:
    url: "http://epicservice:3006"
  taskservice:
    url: "http://taskservice:3005"
  memberservice:
    url: "http://memberservice:3004"
  sprintservice:
    url: "http://sprintservice:3010"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - authservice
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authservice
              changeOrigin: true

  projectPipeline:
    apiEndpoints:
      - projectservice
      - getProjectByslug
      - getProject
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: projectservice
              changeOrigin: true
  userstoryPipeline:
    apiEndpoints:
      - userstoryservice
      - updateuserstory
      - getuserstoriesdetails
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userstoryservice
              changeOrigin: true
  epicPipeline:
    apiEndpoints:
      - epicSerice
      - createEpic
      - listEpics
      - getEpic
      - editEpic
      - deleteEpic
      - createBulkEpics
      - getFiltersData
      - listRelatedUserStories
      - addRelatedUserStory
      - getRelatedUserStory
      - editRelatedUserStory
      - deleteRelatedUserStory
      - bulkCreateRelatedUserStories
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: epicservice
              changeOrigin: true
                        
  taskPipeline:
    apiEndpoints:
      - taskservice
      - deleteTask
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: taskservice
              changeOrigin: true

  memberPipeline:
    apiEndpoints:
      - memberservice
      - getMembers
      - deleteMembers
      - editMemberRole
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: memberservice
              changeOrigin: true      

  sprintPipeline:
    apiEndpoints:
      - sprintservice
      - sprintByID
      - createSprint
      - editSprint
      - deleteSprint
      - sprintByName
      - editSprintByName
      - deleteSprintByName
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: sprintservice
              changeOrigin: true              

