name: Lint CI

on:
  push:
    branches: [develop, master ]
  pull_request:
    branches: [ develop, master]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        dir: ['src/authservice', 'src/projectservice', 'src/taskservice', 'src/userstoryservice', 'src/sprintservice', 'src/epicservice'] 

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        working-directory: ${{ matrix.dir }}
        run : npm install
      - name: Configuring Environment
        working-directory: ${{ matrix.dir }}
        run : npm init @eslint/config
      - name: Code Linting
        working-directory: ${{ matrix.dir }}
        run: npm run lint
