name: Node.js CI

on:
  push:
    branches: [develop, master ]
  pull_request:
    branches: [ develop, master]

jobs:
  build:

    runs-on: ubuntu-latest
      

    strategy:
      matrix:
        node-version: [14.x]
        dir: ['src/authservice', 'src/taskservice'] 

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        working-directory: ${{ matrix.dir }}
        run : npm install
      - name: Running unit test cases
        working-directory: ${{ matrix.dir }}
        run: npm run test
      - name: Running Lint to check static analysis
        working-directory:  ${{ matrix.dir }}
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "master"
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

